# Generated by Django 5.2.4 on 2025-07-29 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0002_tailoredresume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tailoredresume',
            old_name='job_posting',
            new_name='job_posting_url',
        ),
        migrations.RenameField(
            model_name='tailoredresume',
            old_name='source',
            new_name='template_resume',
        ),
    ]
