# Generated by Django 5.2.4 on 2025-07-29 15:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tailor', '0003_rename_job_posting_tailoredresume_job_posting_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='tailoredresume',
            name='unique_resume_name_per_posting_per_user',
        ),
        migrations.AddConstraint(
            model_name='tailoredresume',
            constraint=models.UniqueConstraint(fields=('name', 'job_posting_url', 'user'), name='unique_resume_name_per_posting_per_user'),
        ),
    ]
